package com.thesis.receiptify.model.enums;

import lombok.Getter;

@Getter
public enum IngredientType {
    // VEGETABLES
    ARTICHOKE("Artichoke", "Vegetables"),
    ARUGULA("Arugula", "Vegetables"),
    ASPARAGUS("Asparagus", "Vegetables"),
    AVOCADO("Avocado", "Vegetables"),
    BAMBOO_SHOOTS("Bamboo Shoots", "Vegetables"),
    BEAN_SPROUTS("Bean Sprouts", "Vegetables"),
    BEETS("Beets", "Vegetables"),
    BELL_PEPPER("Bell Pepper", "Vegetables"),
    BOK_CHOY("Bok Choy", "Vegetables"),
    BROCCOLI("Broccoli", "Vegetables"),
    BRUSSELS_SPROUTS("Brussels Sprouts", "Vegetables"),
    CABBAGE("Cabbage", "Vegetables"),
    CARROTS("Carrots", "Vegetables"),
    CAULIFLOWER("Cauliflower", "Vegetables"),
    CELERY("Celery", "Vegetables"),
    CELERY_ROOT("Celery Root", "Vegetables"),
    CHARD("Chard", "Vegetables"),
    CHERRY_TOMATOES("Cherry Tomatoes", "Vegetables"),
    CHIVES("Chives", "Vegetables"),
    COLLARD_GREENS("Collard Greens", "Vegetables"),
    CORN("Corn", "Vegetables"),
    CUCUMBER("Cucumber", "Vegetables"),
    DAIKON_RADISH("Daikon Radish", "Vegetables"),
    EGGPLANT("Eggplant", "Vegetables"),
    ENDIVE("Endive", "Vegetables"),
    FENNEL("Fennel", "Vegetables"),
    GARLIC("Garlic", "Vegetables"),
    GINGER("Ginger", "Vegetables"),
    GREEN_BEANS("Green Beans", "Vegetables"),
    GREEN_ONIONS("Green Onions", "Vegetables"),
    HORSERADISH("Horseradish", "Vegetables"),
    JICAMA("Jicama", "Vegetables"),
    KALE("Kale", "Vegetables"),
    KOHLRABI("Kohlrabi", "Vegetables"),
    LEEKS("Leeks", "Vegetables"),
    LETTUCE("Lettuce", "Vegetables"),
    MUSHROOMS("Mushrooms", "Vegetables"),
    MUSTARD_GREENS("Mustard Greens", "Vegetables"),
    NAPA_CABBAGE("Napa Cabbage", "Vegetables"),
    OKRA("Okra", "Vegetables"),
    ONIONS("Onions", "Vegetables"),
    PARSNIPS("Parsnips", "Vegetables"),
    PEAS("Peas", "Vegetables"),
    POBLANO_PEPPER("Poblano Pepper", "Vegetables"),
    POTATOES("Potatoes", "Vegetables"),
    PUMPKIN("Pumpkin", "Vegetables"),
    RADICCHIO("Radicchio", "Vegetables"),
    RADISHES("Radishes", "Vegetables"),
    RED_ONION("Red Onion", "Vegetables"),
    RHUBARB("Rhubarb", "Vegetables"),
    RUTABAGA("Rutabaga", "Vegetables"),
    SCALLIONS("Scallions", "Vegetables"),
    SHALLOTS("Shallots", "Vegetables"),
    SNAP_PEAS("Snap Peas", "Vegetables"),
    SNOW_PEAS("Snow Peas", "Vegetables"),
    SPINACH("Spinach", "Vegetables"),
    SUMMER_SQUASH("Summer Squash", "Vegetables"),
    SWEET_POTATOES("Sweet Potatoes", "Vegetables"),
    SWISS_CHARD("Swiss Chard", "Vegetables"),
    TOMATILLOS("Tomatillos", "Vegetables"),
    TOMATOES("Tomatoes", "Vegetables"),
    TURNIPS("Turnips", "Vegetables"),
    WATER_CHESTNUTS("Water Chestnuts", "Vegetables"),
    WATERCRESS("Watercress", "Vegetables"),
    WINTER_SQUASH("Winter Squash", "Vegetables"),
    ZUCCHINI("Zucchini", "Vegetables"),

    // FRUITS
    ACAI_BERRIES("Acai Berries", "Fruits"),
    APPLES("Apples", "Fruits"),
    APRICOTS("Apricots", "Fruits"),
    BANANAS("Bananas", "Fruits"),
    BLACKBERRIES("Blackberries", "Fruits"),
    BLUEBERRIES("Blueberries", "Fruits"),
    CANTALOUPE("Cantaloupe", "Fruits"),
    CHERRIES("Cherries", "Fruits"),
    CLEMENTINES("Clementines", "Fruits"),
    COCONUT("Coconut", "Fruits"),
    CRANBERRIES("Cranberries", "Fruits"),
    DATES("Dates", "Fruits"),
    DRAGONFRUIT("Dragonfruit", "Fruits"),
    FIGS("Figs", "Fruits"),
    GOJI_BERRIES("Goji Berries", "Fruits"),
    GRAPEFRUIT("Grapefruit", "Fruits"),
    GRAPES("Grapes", "Fruits"),
    GUAVA("Guava", "Fruits"),
    HONEYDEW_MELON("Honeydew Melon", "Fruits"),
    KIWI("Kiwi", "Fruits"),
    KUMQUATS("Kumquats", "Fruits"),
    LEMONS("Lemons", "Fruits"),
    LIMES("Limes", "Fruits"),
    LYCHEE("Lychee", "Fruits"),
    MANGOES("Mangoes", "Fruits"),
    MANDARINS("Mandarins", "Fruits"),
    NECTARINES("Nectarines", "Fruits"),
    ORANGES("Oranges", "Fruits"),
    PAPAYAS("Papayas", "Fruits"),
    PASSION_FRUIT("Passion Fruit", "Fruits"),
    PEACHES("Peaches", "Fruits"),
    PEARS("Pears", "Fruits"),
    PERSIMMONS("Persimmons", "Fruits"),
    PINEAPPLE("Pineapple", "Fruits"),
    PLUMS("Plums", "Fruits"),
    POMEGRANATE("Pomegranate", "Fruits"),
    RASPBERRIES("Raspberries", "Fruits"),
    STARFRUIT("Starfruit", "Fruits"),
    STRAWBERRIES("Strawberries", "Fruits"),
    TANGERINES("Tangerines", "Fruits"),
    WATERMELON("Watermelon", "Fruits"),

    // PROTEINS
    BACON("Bacon", "Proteins"),
    BEEF_BRISKET("Beef Brisket", "Proteins"),
    BEEF_CHUCK("Beef Chuck", "Proteins"),
    BEEF_GROUND("Ground Beef", "Proteins"),
    BEEF_RIBEYE("Beef Ribeye", "Proteins"),
    BEEF_SIRLOIN("Beef Sirloin", "Proteins"),
    BEEF_TENDERLOIN("Beef Tenderloin", "Proteins"),
    BLACK_BEANS("Black Beans", "Proteins"),
    CANNELLINI_BEANS("Cannellini Beans", "Proteins"),
    CHICKEN_BREAST("Chicken Breast", "Proteins"),
    CHICKEN_DRUMSTICKS("Chicken Drumsticks", "Proteins"),
    CHICKEN_GROUND("Ground Chicken", "Proteins"),
    CHICKEN_THIGHS("Chicken Thighs", "Proteins"),
    CHICKEN_WHOLE("Whole Chicken", "Proteins"),
    CHICKPEAS("Chickpeas", "Proteins"),
    CHORIZO("Chorizo", "Proteins"),
    COD("Cod", "Proteins"),
    CRAB("Crab", "Proteins"),
    DUCK("Duck", "Proteins"),
    EDAMAME("Edamame", "Proteins"),
    FALAFEL("Falafel", "Proteins"),
    GROUND_TURKEY("Ground Turkey", "Proteins"),
    HAM("Ham", "Proteins"),
    KIDNEY_BEANS("Kidney Beans", "Proteins"),
    LAMB_CHOPS("Lamb Chops", "Proteins"),
    LAMB_GROUND("Ground Lamb", "Proteins"),
    LENTILS("Lentils", "Proteins"),
    LIVER("Liver", "Proteins"),
    LOBSTER("Lobster", "Proteins"),
    MUSSELS("Mussels", "Proteins"),
    NAVY_BEANS("Navy Beans", "Proteins"),
    PINTO_BEANS("Pinto Beans", "Proteins"),
    PORK_BELLY("Pork Belly", "Proteins"),
    PORK_CHOPS("Pork Chops", "Proteins"),
    PORK_GROUND("Ground Pork", "Proteins"),
    PORK_LOIN("Pork Loin", "Proteins"),
    PORK_SHOULDER("Pork Shoulder", "Proteins"),
    PROSCIUTTO("Prosciutto", "Proteins"),
    SALMON("Salmon", "Proteins"),
    SALAMI("Salami", "Proteins"),
    SARDINES("Sardines", "Proteins"),
    SAUSAGE("Sausage", "Proteins"),
    SCALLOPS("Scallops", "Proteins"),
    SEITAN("Seitan", "Proteins"),
    SHRIMP("Shrimp", "Proteins"),
    TEMPEH("Tempeh", "Proteins"),
    TILAPIA("Tilapia", "Proteins"),
    TOFU("Tofu", "Proteins"),
    TROUT("Trout", "Proteins"),
    TUNA("Tuna", "Proteins"),
    TURKEY_BREAST("Turkey Breast", "Proteins"),
    VEAL("Veal", "Proteins"),

    // GRAINS & STARCHES
    AMARANTH("Amaranth", "Grains & Starches"),
    BAGELS("Bagels", "Grains & Starches"),
    BARLEY("Barley", "Grains & Starches"),
    BREAD_CRUMBS("Bread Crumbs", "Grains & Starches"),
    BREAD_SOURDOUGH("Sourdough Bread", "Grains & Starches"),
    BREAD_WHITE("White Bread", "Grains & Starches"),
    BREAD_WHOLE_WHEAT("Whole Wheat Bread", "Grains & Starches"),
    BROWN_RICE("Brown Rice", "Grains & Starches"),
    BUCKWHEAT("Buckwheat", "Grains & Starches"),
    BULGUR("Bulgur", "Grains & Starches"),
    COUSCOUS("Couscous", "Grains & Starches"),
    CRACKERS("Crackers", "Grains & Starches"),
    CROISSANTS("Croissants", "Grains & Starches"),
    ENGLISH_MUFFINS("English Muffins", "Grains & Starches"),
    FARRO("Farro", "Grains & Starches"),
    FLOUR_ALL_PURPOSE("All-Purpose Flour", "Grains & Starches"),
    FLOUR_ALMOND("Almond Flour", "Grains & Starches"),
    FLOUR_BREAD("Bread Flour", "Grains & Starches"),
    FLOUR_CAKE("Cake Flour", "Grains & Starches"),
    FLOUR_CHICKPEA("Chickpea Flour", "Grains & Starches"),
    FLOUR_COCONUT("Coconut Flour", "Grains & Starches"),
    FLOUR_CORN("Corn Flour", "Grains & Starches"),
    FLOUR_OAT("Oat Flour", "Grains & Starches"),
    FLOUR_PASTRY("Pastry Flour", "Grains & Starches"),
    FLOUR_RYE("Rye Flour", "Grains & Starches"),
    FLOUR_WHOLE_WHEAT("Whole Wheat Flour", "Grains & Starches"),
    JASMINE_RICE("Jasmine Rice", "Grains & Starches"),
    MILLET("Millet", "Grains & Starches"),
    NAAN_BREAD("Naan Bread", "Grains & Starches"),
    OATS_ROLLED("Rolled Oats", "Grains & Starches"),
    OATS_STEEL_CUT("Steel Cut Oats", "Grains & Starches"),
    PASTA_ANGEL_HAIR("Angel Hair Pasta", "Grains & Starches"),
    PASTA_FETTUCCINE("Fettuccine", "Grains & Starches"),
    PASTA_LASAGNA("Lasagna Noodles", "Grains & Starches"),
    PASTA_MACARONI("Macaroni", "Grains & Starches"),
    PASTA_ORZO("Orzo", "Grains & Starches"),
    PASTA_PENNE("Penne", "Grains & Starches"),
    PASTA_RIGATONI("Rigatoni", "Grains & Starches"),
    PASTA_SHELLS("Pasta Shells", "Grains & Starches"),
    PASTA_SPAGHETTI("Spaghetti", "Grains & Starches"),
    PITA_BREAD("Pita Bread", "Grains & Starches"),
    POLENTA("Polenta", "Grains & Starches"),
    QUINOA("Quinoa", "Grains & Starches"),
    RICE_FLOUR("Rice Flour", "Grains & Starches"),
    RICE_WILD("Wild Rice", "Grains & Starches"),
    RYE_BREAD("Rye Bread", "Grains & Starches"),
    SEMOLINA("Semolina", "Grains & Starches"),
    SPELT("Spelt", "Grains & Starches"),
    TORTILLAS_CORN("Corn Tortillas", "Grains & Starches"),
    TORTILLAS_FLOUR("Flour Tortillas", "Grains & Starches"),
    WHITE_RICE("White Rice", "Grains & Starches"),

    AMERICAN_CHEESE("American Cheese", "Dairy & Eggs"),
    BLUE_CHEESE("Blue Cheese", "Dairy & Eggs"),
    BRIE("Brie", "Dairy & Eggs"),
    BUTTER("Butter", "Dairy & Eggs"),
    BUTTERMILK("Buttermilk", "Dairy & Eggs"),
    CAMEMBERT("Camembert", "Dairy & Eggs"),
    CHEDDAR_CHEESE("Cheddar Cheese", "Dairy & Eggs"),
    COTTAGE_CHEESE("Cottage Cheese", "Dairy & Eggs"),
    CREAM("Heavy Cream", "Dairy & Eggs"),
    CREAM_CHEESE("Cream Cheese", "Dairy & Eggs"),
    DUCK_EGGS("Duck Eggs", "Dairy & Eggs"),
    EGGS("Eggs", "Dairy & Eggs"),
    EGG_WHITES("Egg Whites", "Dairy & Eggs"),
    EGG_YOLKS("Egg Yolks", "Dairy & Eggs"),
    EVAPORATED_MILK("Evaporated Milk", "Dairy & Eggs"),
    FETA_CHEESE("Feta Cheese", "Dairy & Eggs"),
    GOAT_CHEESE("Goat Cheese", "Dairy & Eggs"),
    GOUDA("Gouda", "Dairy & Eggs"),
    GRUYERE("Gruyere", "Dairy & Eggs"),
    HALF_AND_HALF("Half and Half", "Dairy & Eggs"),
    ICE_CREAM("Ice Cream", "Dairy & Eggs"),
    KEFIR("Kefir", "Dairy & Eggs"),
    MASCARPONE("Mascarpone", "Dairy & Eggs"),
    MILK("Milk", "Dairy & Eggs"),
    MILK_ALMOND("Almond Milk", "Dairy & Eggs"),
    MILK_COCONUT("Coconut Milk", "Dairy & Eggs"),
    MILK_CONDENSED("Condensed Milk", "Dairy & Eggs"),
    MILK_OAT("Oat Milk", "Dairy & Eggs"),
    MILK_SOY("Soy Milk", "Dairy & Eggs"),
    MONTEREY_JACK("Monterey Jack", "Dairy & Eggs"),
    MOZZARELLA("Mozzarella", "Dairy & Eggs"),
    PARMESAN_CHEESE("Parmesan Cheese", "Dairy & Eggs"),
    PROVOLONE("Provolone", "Dairy & Eggs"),
    QUARK("Quark", "Dairy & Eggs"),
    QUAIL_EGGS("Quail Eggs", "Dairy & Eggs"),
    QUESO_FRESCO("Queso Fresco", "Dairy & Eggs"),
    RICOTTA_CHEESE("Ricotta Cheese", "Dairy & Eggs"),
    SOUR_CREAM("Sour Cream", "Dairy & Eggs"),
    SWISS_CHEESE("Swiss Cheese", "Dairy & Eggs"),
    WHIPPED_CREAM("Whipped Cream", "Dairy & Eggs"),
    YOGURT_GREEK("Greek Yogurt", "Dairy & Eggs"),
    YOGURT_PLAIN("Plain Yogurt", "Dairy & Eggs"),

    // HERBS & SPICES
    ALLSPICE("Allspice", "Herbs & Spices"),
    ANISE("Anise", "Herbs & Spices"),
    BASIL("Basil", "Herbs & Spices"),
    BAY_LEAVES("Bay Leaves", "Herbs & Spices"),
    BLACK_PEPPER("Black Pepper", "Herbs & Spices"),
    CARDAMOM("Cardamom", "Herbs & Spices"),
    CAYENNE_PEPPER("Cayenne Pepper", "Herbs & Spices"),
    CELERY_SEEDS("Celery Seeds", "Herbs & Spices"),
    CHILI_FLAKES("Chili Flakes", "Herbs & Spices"),
    CHILI_POWDER("Chili Powder", "Herbs & Spices"),
    CILANTRO("Cilantro", "Herbs & Spices"),
    CINNAMON("Cinnamon", "Herbs & Spices"),
    CLOVES("Cloves", "Herbs & Spices"),
    CORIANDER("Coriander", "Herbs & Spices"),
    CUMIN("Cumin", "Herbs & Spices"),
    CURRY_POWDER("Curry Powder", "Herbs & Spices"),
    DILL("Dill", "Herbs & Spices"),
    FENNEL_SEEDS("Fennel Seeds", "Herbs & Spices"),
    FENUGREEK("Fenugreek", "Herbs & Spices"),
    FIVE_SPICE("Five Spice", "Herbs & Spices"),
    GARLIC_POWDER("Garlic Powder", "Herbs & Spices"),
    GARAM_MASALA("Garam Masala", "Herbs & Spices"),
    GINGER_GROUND("Ground Ginger", "Herbs & Spices"),
    HERBES_DE_PROVENCE("Herbes de Provence", "Herbs & Spices"),
    LEMONGRASS("Lemongrass", "Herbs & Spices"),
    MARJORAM("Marjoram", "Herbs & Spices"),
    MINT("Mint", "Herbs & Spices"),
    MUSTARD_POWDER("Mustard Powder", "Herbs & Spices"),
    MUSTARD_SEEDS("Mustard Seeds", "Herbs & Spices"),
    NUTMEG("Nutmeg", "Herbs & Spices"),
    ONION_POWDER("Onion Powder", "Herbs & Spices"),
    OREGANO("Oregano", "Herbs & Spices"),
    PAPRIKA("Paprika", "Herbs & Spices"),
    PARSLEY("Parsley", "Herbs & Spices"),
    PEPPERCORNS("Peppercorns", "Herbs & Spices"),
    POPPY_SEEDS("Poppy Seeds", "Herbs & Spices"),
    RED_PEPPER_FLAKES("Red Pepper Flakes", "Herbs & Spices"),
    ROSEMARY("Rosemary", "Herbs & Spices"),
    SAFFRON("Saffron", "Herbs & Spices"),
    SAGE("Sage", "Herbs & Spices"),
    SALT_KOSHER("Kosher Salt", "Herbs & Spices"),
    SALT_SEA("Sea Salt", "Herbs & Spices"),
    SALT_TABLE("Table Salt", "Herbs & Spices"),
    STAR_ANISE("Star Anise", "Herbs & Spices"),
    SUMAC("Sumac", "Herbs & Spices"),
    TARRAGON("Tarragon", "Herbs & Spices"),
    THYME("Thyme", "Herbs & Spices"),
    TURMERIC("Turmeric", "Herbs & Spices"),
    VANILLA_BEANS("Vanilla Beans", "Herbs & Spices"),
    WHITE_PEPPER("White Pepper", "Herbs & Spices"),
    ZA_ATAR("Za'atar", "Herbs & Spices"),

    // OILS, VINEGARS & CONDIMENTS
    AIOLI("Aioli", "Oils, Vinegars & Condiments"),
    APPLE_CIDER_VINEGAR("Apple Cider Vinegar", "Oils, Vinegars & Condiments"),
    AVOCADO_OIL("Avocado Oil", "Oils, Vinegars & Condiments"),
    BALSAMIC_GLAZE("Balsamic Glaze", "Oils, Vinegars & Condiments"),
    BALSAMIC_VINEGAR("Balsamic Vinegar", "Oils, Vinegars & Condiments"),
    BARBECUE_SAUCE("Barbecue Sauce", "Oils, Vinegars & Condiments"),
    CANOLA_OIL("Canola Oil", "Oils, Vinegars & Condiments"),
    CAPERS("Capers", "Oils, Vinegars & Condiments"),
    CHAMPAGNE_VINEGAR("Champagne Vinegar", "Oils, Vinegars & Condiments"),
    CHILI_OIL("Chili Oil", "Oils, Vinegars & Condiments"),
    CHILI_SAUCE("Chili Sauce", "Oils, Vinegars & Condiments"),
    COCONUT_OIL("Coconut Oil", "Oils, Vinegars & Condiments"),
    DIJON_MUSTARD("Dijon Mustard", "Oils, Vinegars & Condiments"),
    FISH_SAUCE("Fish Sauce", "Oils, Vinegars & Condiments"),
    GHEE("Ghee", "Oils, Vinegars & Condiments"),
    GOCHUJANG("Gochujang", "Oils, Vinegars & Condiments"),
    HARISSA("Harissa", "Oils, Vinegars & Condiments"),
    HOISIN_SAUCE("Hoisin Sauce", "Oils, Vinegars & Condiments"),
    HOT_SAUCE("Hot Sauce", "Oils, Vinegars & Condiments"),
    KETCHUP("Ketchup", "Oils, Vinegars & Condiments"),
    KIMCHI("Kimchi", "Oils, Vinegars & Condiments"),
    LARD("Lard", "Oils, Vinegars & Condiments"),
    MALT_VINEGAR("Malt Vinegar", "Oils, Vinegars & Condiments"),
    MAYONNAISE("Mayonnaise", "Oils, Vinegars & Condiments"),
    MIRIN("Mirin", "Oils, Vinegars & Condiments"),
    MISO_PASTE("Miso Paste", "Oils, Vinegars & Condiments"),
    OLIVE_OIL_EXTRA_VIRGIN("Extra Virgin Olive Oil", "Oils, Vinegars & Condiments"),
    OYSTER_SAUCE("Oyster Sauce", "Oils, Vinegars & Condiments"),
    PEANUT_OIL("Peanut Oil", "Oils, Vinegars & Condiments"),
    PESTO("Pesto", "Oils, Vinegars & Condiments"),
    PICKLE_RELISH("Pickle Relish", "Oils, Vinegars & Condiments"),
    PICKLES("Pickles", "Oils, Vinegars & Condiments"),
    RED_WINE_VINEGAR("Red Wine Vinegar", "Oils, Vinegars & Condiments"),
    RICE_VINEGAR("Rice Vinegar", "Oils, Vinegars & Condiments"),
    RICE_WINE("Rice Wine", "Oils, Vinegars & Condiments"),
    SALSA("Salsa", "Oils, Vinegars & Condiments"),
    SESAME_OIL("Sesame Oil", "Oils, Vinegars & Condiments"),
    SHERRY_VINEGAR("Sherry Vinegar", "Oils, Vinegars & Condiments"),
    SOY_SAUCE("Soy Sauce", "Oils, Vinegars & Condiments"),
    SRIRACHA("Sriracha", "Oils, Vinegars & Condiments"),
    TAHINI("Tahini", "Oils, Vinegars & Condiments"),
    TAMARI("Tamari", "Oils, Vinegars & Condiments"),
    TERIYAKI_SAUCE("Teriyaki Sauce", "Oils, Vinegars & Condiments"),
    VEGETABLE_OIL("Vegetable Oil", "Oils, Vinegars & Condiments"),
    VINEGAR_WHITE("White Vinegar", "Oils, Vinegars & Condiments"),
    WALNUT_OIL("Walnut Oil", "Oils, Vinegars & Condiments"),
    WHITE_WINE_VINEGAR("White Wine Vinegar", "Oils, Vinegars & Condiments"),
    WORCESTERSHIRE_SAUCE("Worcestershire Sauce", "Oils, Vinegars & Condiments"),

    // NUTS, SEEDS & DRIED FRUITS
    ALMONDS("Almonds", "Nuts, Seeds & Dried Fruits"),
    BRAZIL_NUTS("Brazil Nuts", "Nuts, Seeds & Dried Fruits"),
    CASHEWS("Cashews", "Nuts, Seeds & Dried Fruits"),
    CHIA_SEEDS("Chia Seeds", "Nuts, Seeds & Dried Fruits"),
    DRIED_APPLES("Dried Apples", "Nuts, Seeds & Dried Fruits"),
    DRIED_APRICOTS("Dried Apricots", "Nuts, Seeds & Dried Fruits"),
    DRIED_CRANBERRIES("Dried Cranberries", "Nuts, Seeds & Dried Fruits"),
    DRIED_DATES("Dried Dates", "Nuts, Seeds & Dried Fruits"),
    DRIED_FIGS("Dried Figs", "Nuts, Seeds & Dried Fruits"),
    DRIED_MANGOES("Dried Mangoes", "Nuts, Seeds & Dried Fruits"),
    DRIED_PINEAPPLE("Dried Pineapple", "Nuts, Seeds & Dried Fruits"),
    FLAXSEEDS("Flaxseeds", "Nuts, Seeds & Dried Fruits"),
    HAZELNUTS("Hazelnuts", "Nuts, Seeds & Dried Fruits"),
    HEMP_SEEDS("Hemp Seeds", "Nuts, Seeds & Dried Fruits"),
    MACADAMIA_NUTS("Macadamia Nuts", "Nuts, Seeds & Dried Fruits"),
    PEANUTS("Peanuts", "Nuts, Seeds & Dried Fruits"),
    PECANS("Pecans", "Nuts, Seeds & Dried Fruits"),
    PINE_NUTS("Pine Nuts", "Nuts, Seeds & Dried Fruits"),
    PISTACHIOS("Pistachios", "Nuts, Seeds & Dried Fruits"),
    PUMPKIN_SEEDS("Pumpkin Seeds", "Nuts, Seeds & Dried Fruits"),
    RAISINS("Raisins", "Nuts, Seeds & Dried Fruits"),
    SESAME_SEEDS("Sesame Seeds", "Nuts, Seeds & Dried Fruits"),
    SUNFLOWER_SEEDS("Sunflower Seeds", "Nuts, Seeds & Dried Fruits"),
    WALNUTS("Walnuts", "Nuts, Seeds & Dried Fruits"),

    // SWEETENERS & BAKING
    AGAVE_NECTAR("Agave Nectar", "Sweeteners & Baking"),
    BAKING_POWDER("Baking Powder", "Sweeteners & Baking"),
    BAKING_SODA("Baking Soda", "Sweeteners & Baking"),
    BROWN_SUGAR("Brown Sugar", "Sweeteners & Baking"),
    CACAO_NIBS("Cacao Nibs", "Sweeteners & Baking"),
    CACAO_POWDER("Cacao Powder", "Sweeteners & Baking"),
    CHOCOLATE_CHIPS("Chocolate Chips", "Sweeteners & Baking"),
    CHOCOLATE_DARK("Dark Chocolate", "Sweeteners & Baking"),
    CHOCOLATE_MILK("Milk Chocolate", "Sweeteners & Baking"),
    CHOCOLATE_WHITE("White Chocolate", "Sweeteners & Baking"),
    COCOA_POWDER("Cocoa Powder", "Sweeteners & Baking"),
    COCONUT_SUGAR("Coconut Sugar", "Sweeteners & Baking"),
    CONFECTIONERS_SUGAR("Confectioners Sugar", "Sweeteners & Baking"),
    CORN_STARCH("Corn Starch", "Sweeteners & Baking"),
    CORN_SYRUP("Corn Syrup", "Sweeteners & Baking"),
    DATE_SUGAR("Date Sugar", "Sweeteners & Baking"),
    GRANULATED_SUGAR("Granulated Sugar", "Sweeteners & Baking"),
    HONEY("Honey", "Sweeteners & Baking"),
    MAPLE_SUGAR("Maple Sugar", "Sweeteners & Baking"),
    MAPLE_SYRUP("Maple Syrup", "Sweeteners & Baking"),
    MOLASSES("Molasses", "Sweeteners & Baking"),
    POTATO_STARCH("Potato Starch", "Sweeteners & Baking"),
    RAW_SUGAR("Raw Sugar", "Sweeteners & Baking"),
    RICE_SYRUP("Rice Syrup", "Sweeteners & Baking"),
    STEVIA("Stevia", "Sweeteners & Baking"),
    TAPIOCA_STARCH("Tapioca Starch", "Sweeteners & Baking"),
    VANILLA_EXTRACT("Vanilla Extract", "Sweeteners & Baking"),
    VANILLA_PASTE("Vanilla Paste", "Sweeteners & Baking"),
    XANTHAN_GUM("Xanthan Gum", "Sweeteners & Baking"),
    YEAST_ACTIVE_DRY("Active Dry Yeast", "Sweeteners & Baking"),
    YEAST_INSTANT("Instant Yeast", "Sweeteners & Baking"),

    // BEVERAGES & ALCOHOLIC INGREDIENTS
    ALMOND_MILK("Almond Milk", "Beverages & Alcoholic Ingredients"),
    AMARETTO("Amaretto", "Beverages & Alcoholic Ingredients"),
    BEER("Beer", "Beverages & Alcoholic Ingredients"),
    BOURBON("Bourbon", "Beverages & Alcoholic Ingredients"),
    BRANDY("Brandy", "Beverages & Alcoholic Ingredients"),
    CHAMPAGNE("Champagne", "Beverages & Alcoholic Ingredients"),
    CLUB_SODA("Club Soda", "Beverages & Alcoholic Ingredients"),
    COCONUT_WATER("Coconut Water", "Beverages & Alcoholic Ingredients"),
    COFFEE("Coffee", "Beverages & Alcoholic Ingredients"),
    COGNAC("Cognac", "Beverages & Alcoholic Ingredients"),
    COINTREAU("Cointreau", "Beverages & Alcoholic Ingredients"),
    ESPRESSO("Espresso", "Beverages & Alcoholic Ingredients"),
    GIN("Gin", "Beverages & Alcoholic Ingredients"),
    GRAND_MARNIER("Grand Marnier", "Beverages & Alcoholic Ingredients"),
    KAHLUA("Kahlua", "Beverages & Alcoholic Ingredients"),
    KIRSCH("Kirsch", "Beverages & Alcoholic Ingredients"),
    LIMONCELLO("Limoncello", "Beverages & Alcoholic Ingredients"),
    MARSALA_WINE("Marsala Wine", "Beverages & Alcoholic Ingredients"),
    PORT_WINE("Port Wine", "Beverages & Alcoholic Ingredients"),
    RED_WINE("Red Wine", "Beverages & Alcoholic Ingredients"),
    RUM_DARK("Dark Rum", "Beverages & Alcoholic Ingredients"),
    RUM_WHITE("White Rum", "Beverages & Alcoholic Ingredients"),
    SAKE("Sake", "Beverages & Alcoholic Ingredients"),
    SHERRY("Sherry", "Beverages & Alcoholic Ingredients"),
    TEA("Tea", "Beverages & Alcoholic Ingredients"),
    TEQUILA("Tequila", "Beverages & Alcoholic Ingredients"),
    TRIPLE_SEC("Triple Sec", "Beverages & Alcoholic Ingredients"),
    VERMOUTH_DRY("Dry Vermouth", "Beverages & Alcoholic Ingredients"),
    VERMOUTH_SWEET("Sweet Vermouth", "Beverages & Alcoholic Ingredients"),
    VODKA("Vodka", "Beverages & Alcoholic Ingredients"),
    WHISKEY("Whiskey", "Beverages & Alcoholic Ingredients"),
    WHITE_WINE("White Wine", "Beverages & Alcoholic Ingredients"),
    WINE_COOKING("Cooking Wine", "Beverages & Alcoholic Ingredients"),

    // CANNED & JARRED GOODS
    ANCHOVIES("Anchovies", "Canned & Jarred Goods"),
    ARTICHOKE_HEARTS("Artichoke Hearts", "Canned & Jarred Goods"),
    BAKED_BEANS("Baked Beans", "Canned & Jarred Goods"),
    BAMBOO_SHOOTS_CANNED("Canned Bamboo Shoots", "Canned & Jarred Goods"),
    BLACK_BEANS_CANNED("Canned Black Beans", "Canned & Jarred Goods"),
    BLACK_OLIVES("Black Olives", "Canned & Jarred Goods"),
    CANNELLINI_BEANS_CANNED("Canned Cannellini Beans", "Canned & Jarred Goods"),
    CHICKPEAS_CANNED("Canned Chickpeas", "Canned & Jarred Goods"),
    CHIPOTLE_PEPPERS_ADOBO("Chipotle Peppers in Adobo", "Canned & Jarred Goods"),
    COCONUT_CREAM("Coconut Cream", "Canned & Jarred Goods"),
    COCONUT_MILK_CANNED("Canned Coconut Milk", "Canned & Jarred Goods"),
    CORN_CANNED("Canned Corn", "Canned & Jarred Goods"),
    CRAB_MEAT_CANNED("Canned Crab Meat", "Canned & Jarred Goods"),
    DICED_TOMATOES("Diced Tomatoes", "Canned & Jarred Goods"),
    GREEN_BEANS_CANNED("Canned Green Beans", "Canned & Jarred Goods"),
    GREEN_CHILIES_CANNED("Canned Green Chilies", "Canned & Jarred Goods"),
    GREEN_OLIVES("Green Olives", "Canned & Jarred Goods"),
    HEARTS_OF_PALM("Hearts of Palm", "Canned & Jarred Goods"),
    KIDNEY_BEANS_CANNED("Canned Kidney Beans", "Canned & Jarred Goods"),
    MANDARIN_ORANGES("Mandarin Oranges", "Canned & Jarred Goods"),
    MARINARA_SAUCE("Marinara Sauce", "Canned & Jarred Goods"),
    MUSHROOMS_CANNED("Canned Mushrooms", "Canned & Jarred Goods"),
    PEAS_CANNED("Canned Peas", "Canned & Jarred Goods"),
    PINEAPPLE_CANNED("Canned Pineapple", "Canned & Jarred Goods"),
    PINTO_BEANS_CANNED("Canned Pinto Beans", "Canned & Jarred Goods"),
    PUMPKIN_PUREE("Pumpkin Puree", "Canned & Jarred Goods"),
    ROASTED_RED_PEPPERS("Roasted Red Peppers", "Canned & Jarred Goods"),
    SALSA_JARRED("Jarred Salsa", "Canned & Jarred Goods"),
    SAUERKRAUT("Sauerkraut", "Canned & Jarred Goods"),
    SPAGHETTI_SAUCE("Spaghetti Sauce", "Canned & Jarred Goods"),
    SUN_DRIED_TOMATOES("Sun-Dried Tomatoes", "Canned & Jarred Goods"),
    TOMATO_PASTE("Tomato Paste", "Canned & Jarred Goods"),
    TOMATO_PUREE("Tomato Puree", "Canned & Jarred Goods"),
    TOMATO_SAUCE("Tomato Sauce", "Canned & Jarred Goods"),
    TUNA_CANNED("Canned Tuna", "Canned & Jarred Goods"),
    WATER_CHESTNUTS_CANNED("Canned Water Chestnuts", "Canned & Jarred Goods"),

    // FROZEN FOODS
    ACAI_PUREE_FROZEN("Frozen Acai Puree", "Frozen Foods"),
    BERRIES_FROZEN("Frozen Mixed Berries", "Frozen Foods"),
    BLUEBERRIES_FROZEN("Frozen Blueberries", "Frozen Foods"),
    BROCCOLI_FROZEN("Frozen Broccoli", "Frozen Foods"),
    CAULIFLOWER_FROZEN("Frozen Cauliflower", "Frozen Foods"),
    CORN_FROZEN("Frozen Corn", "Frozen Foods"),
    EDAMAME_FROZEN("Frozen Edamame", "Frozen Foods"),
    FRENCH_FRIES_FROZEN("Frozen French Fries", "Frozen Foods"),
    MANGO_FROZEN("Frozen Mango", "Frozen Foods"),
    MIXED_VEGETABLES_FROZEN("Frozen Mixed Vegetables", "Frozen Foods"),
    PEAS_FROZEN("Frozen Peas", "Frozen Foods"),
    PUFF_PASTRY("Puff Pastry", "Frozen Foods"),
    SPINACH_FROZEN("Frozen Spinach", "Frozen Foods"),
    STRAWBERRIES_FROZEN("Frozen Strawberries", "Frozen Foods"),
    VEGGIE_BURGERS_FROZEN("Frozen Veggie Burgers", "Frozen Foods"),
    WAFFLES_FROZEN("Frozen Waffles", "Frozen Foods"),

    // INTERNATIONAL INGREDIENTS
    ADOBO_SEASONING("Adobo Seasoning", "International Ingredients"),
    CURRY_LEAVES("Curry Leaves", "International Ingredients"),
    DUMPLING_WRAPPERS("Dumpling Wrappers", "International Ingredients"),
    FILO_DOUGH("Filo Dough", "International Ingredients"),
    FURIKAKE("Furikake", "International Ingredients"),
    GOCHUGARU("Gochugaru", "International Ingredients"),
    HALLOUMI("Halloumi", "International Ingredients"),
    HARISSA_PASTE("Harissa Paste", "International Ingredients"),
    NORI_SHEETS("Nori Sheets", "International Ingredients"),
    PANKO_BREADCRUMBS("Panko Breadcrumbs", "International Ingredients"),
    RED_CURRY_PASTE("Red Curry Paste", "International Ingredients"),
    RICE_PAPER_WRAPPERS("Rice Paper Wrappers", "International Ingredients"),
    SAMBAL_OELEK("Sambal Oelek", "International Ingredients"),
    SHRIMP_PASTE("Shrimp Paste", "International Ingredients"),
    TAMARIND_PASTE("Tamarind Paste", "International Ingredients"),
    WASABI("Wasabi", "International Ingredients"),
    YUZU_JUICE("Yuzu Juice", "International Ingredients"),

    // MISCELLANEOUS
    CHICKEN_BROTH("Chicken Broth", "Miscellaneous"),
    CHOCOLATE_SYRUP("Chocolate Syrup", "Miscellaneous"),
    COOKING_SPRAY("Cooking Spray", "Miscellaneous"),
    GELATIN("Gelatin", "Miscellaneous"),
    HORSERADISH_PREPARED("Prepared Horseradish", "Miscellaneous"),
    ICE("Ice", "Miscellaneous"),
    NUTRITIONAL_YEAST("Nutritional Yeast", "Miscellaneous"),
    OLIVES_STUFFED("Stuffed Olives", "Miscellaneous"),
    PECTIN("Pectin", "Miscellaneous"),
    PROTEIN_POWDER("Protein Powder", "Miscellaneous"),
    VEGETABLE_BROTH("Vegetable Broth", "Miscellaneous"),
    WATER("Water", "Miscellaneous");

    private final String displayName;
    private final String category;

    IngredientType(String displayName, String category) {
        this.displayName = displayName;
        this.category = category;
    }

    public static IngredientType fromDisplayName(String displayName) {
        for (IngredientType type : values()) {
            if (type.getDisplayName().equalsIgnoreCase(displayName)) {
                return type;
            }
        }
        return null;
    }
}
